# Keras Basics     

* Let's learn how to create a very simple neural network for classifying the famous Iris dataset.   
* The dataset contains measurements of flower petals, and sepals, and their corresponding labels to one of the three classes (3 flower species)

In [11]:
#%%bash
#pip install keras

In [14]:
#%%bash
#pip install tensorflow 

In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
X = iris.data
y = iris.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [48]:
## One-hot encoding for the labels
# class 0 --> [1, 0, 0]
# class 1 --> [0, 1, 0]
# class 2 --> [0, 0, 1]
from keras.utils import to_categorical

In [16]:
y = to_categorical(y)

In [17]:
y.shape

(150, 3)

In [19]:
# y

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.33, random_state=42)

In [22]:
# For neural net, it is good to scale or standardize the data 
from sklearn.preprocessing import MinMaxScaler

In [23]:
scaler_object = MinMaxScaler()

In [25]:
# We perform fit Scaling on ONLY TRAINING DATA
scaler_object.fit(X_train)

MinMaxScaler()

In [26]:
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

In [42]:
# Useful keras libraries
from keras.models import Sequential
from keras.layers import Dense

In [28]:
# Build the network
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax')) # --> Gives Probability values for each class
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [29]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.fit(scaled_X_train, y_train, epochs=200, verbose=2)

Epoch 1/200
 - 0s - loss: 1.1128 - accuracy: 0.3400
Epoch 2/200
 - 0s - loss: 1.1088 - accuracy: 0.3200
Epoch 3/200
 - 0s - loss: 1.1050 - accuracy: 0.3200
Epoch 4/200
 - 0s - loss: 1.1017 - accuracy: 0.3100
Epoch 5/200
 - 0s - loss: 1.0984 - accuracy: 0.3100
Epoch 6/200
 - 0s - loss: 1.0954 - accuracy: 0.3200
Epoch 7/200
 - 0s - loss: 1.0936 - accuracy: 0.3200
Epoch 8/200
 - 0s - loss: 1.0920 - accuracy: 0.3500
Epoch 9/200
 - 0s - loss: 1.0905 - accuracy: 0.3400
Epoch 10/200
 - 0s - loss: 1.0890 - accuracy: 0.3200
Epoch 11/200
 - 0s - loss: 1.0875 - accuracy: 0.3100
Epoch 12/200
 - 0s - loss: 1.0860 - accuracy: 0.3200
Epoch 13/200
 - 0s - loss: 1.0844 - accuracy: 0.3200
Epoch 14/200
 - 0s - loss: 1.0827 - accuracy: 0.3200
Epoch 15/200
 - 0s - loss: 1.0810 - accuracy: 0.3300
Epoch 16/200
 - 0s - loss: 1.0793 - accuracy: 0.3400
Epoch 17/200
 - 0s - loss: 1.0776 - accuracy: 0.3500
Epoch 18/200
 - 0s - loss: 1.0758 - accuracy: 0.3300
Epoch 19/200
 - 0s - loss: 1.0739 - accuracy: 0.3300
Ep

Epoch 155/200
 - 0s - loss: 0.3978 - accuracy: 0.9100
Epoch 156/200
 - 0s - loss: 0.3952 - accuracy: 0.9000
Epoch 157/200
 - 0s - loss: 0.3923 - accuracy: 0.9000
Epoch 158/200
 - 0s - loss: 0.3896 - accuracy: 0.9300
Epoch 159/200
 - 0s - loss: 0.3853 - accuracy: 0.9400
Epoch 160/200
 - 0s - loss: 0.3822 - accuracy: 0.9400
Epoch 161/200
 - 0s - loss: 0.3794 - accuracy: 0.9400
Epoch 162/200
 - 0s - loss: 0.3761 - accuracy: 0.9400
Epoch 163/200
 - 0s - loss: 0.3733 - accuracy: 0.9400
Epoch 164/200
 - 0s - loss: 0.3706 - accuracy: 0.9400
Epoch 165/200
 - 0s - loss: 0.3669 - accuracy: 0.9400
Epoch 166/200
 - 0s - loss: 0.3640 - accuracy: 0.9400
Epoch 167/200
 - 0s - loss: 0.3606 - accuracy: 0.9500
Epoch 168/200
 - 0s - loss: 0.3575 - accuracy: 0.9600
Epoch 169/200
 - 0s - loss: 0.3559 - accuracy: 0.9600
Epoch 170/200
 - 0s - loss: 0.3539 - accuracy: 0.9700
Epoch 171/200
 - 0s - loss: 0.3531 - accuracy: 0.9600
Epoch 172/200
 - 0s - loss: 0.3512 - accuracy: 0.9700
Epoch 173/200
 - 0s - loss: 

In [31]:
model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [32]:
predictions = model.predict_classes(scaled_X_test)

In [33]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [34]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [35]:
print(confusion_matrix(y_test.argmax(axis=1), predictions))

[[19  0  0]
 [ 0 14  1]
 [ 0  0 16]]


In [36]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.93      0.97        15
           2       0.94      1.00      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [37]:
print(accuracy_score(y_test.argmax(axis=1), predictions))

0.98


In [43]:
model.save("mykeras_model.h5")

In [44]:
from keras.models import load_model

In [45]:
new_model = load_model('mykeras_model.h5')

In [46]:
new_model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])